jobs:
- sparkJob:
   jarFileUris:
   - gs://fcr-prediction-resources/dataproc-test-dash-test/dataprocJavaDemo-1.0-SNAPSHOT.jar
   mainClass: org.example.dataproc.InternationalLoansAppDataprocSmall
 stepId: ibrd-small-spark
- sparkJob:
   jarFileUris:
   - gs://fcr-prediction-resources/dataproc-test-dash-test/dataprocJavaDemo-1.0-SNAPSHOT.jar
   mainClass: org.example.dataproc.InternationalLoansAppDataprocLarge
 stepId: ibrd-large-spark
- pysparkJob:
   args:
   - gs://fcr-prediction-resources/dataproc-test-dash-test/
   - ibrd-statement-of-loans-historical-data.csv
   - ibrd-summary-large-python
   mainPythonFileUri: gs://fcr-prediction-resources/dataproc-test-dash-test/international_loans_dataproc.py
 stepId: ibrd-large-pyspark
placement:
 managedCluster:
   clusterName: dataproc-monitoring-cluster
   config:
     gceClusterConfig:
       internalIpOnly: True
       subnetworkUri: dataproc-standalone-paasonly-europe-west2
       tags:
           - dataproc
       zoneUri: https://www.googleapis.com/compute/v1/projects/hsbc-7337771-fcr-dev/zones/europe-west2-a
       serviceAccount: ilfcrm-dataproc-controller@hsbc-7337771-fcr-dev.iam.gserviceaccount.com
     masterConfig:
       diskConfig:
         bootDiskSizeGb: 20
       machineTypeUri: n1-standard-4
     workerConfig:
       diskConfig:
         bootDiskSizeGb: 20
       machineTypeUri: n1-standard-4
       numInstances: 2
     softwareConfig:
       imageVersion: '1.4'
       properties:
         dataproc:dataproc.logging.stackdriver.job.driver.enable: "true"
         dataproc:dataproc.logging.stackdriver.enable: "true"
         dataproc:jobs.file-backed-output.enable: "true"
         dataproc:dataproc.logging.stackdriver.job.yarn.container.enable: "true"
         dataproc:dataproc.monitoring.stackdriver.enable: "true"
         spark:spark.submit.deployMode: "cluster"
